name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory and add key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa_new
          chmod 600 ~/.ssh/id_rsa_new
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Start ssh-agent and add SSH key
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa_new

      - name: Add server to known_hosts
        run: ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
        env:
          VPS_IP: ${{ secrets.VPS_IP }}

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa_new -o StrictHostKeyChecking=no $SSH_USER@$VPS_IP << 'EOF'
          cd /var/www/adminci.infranetmp.com
          sudo git pull origin main
          composer install --no-interaction --prefer-dist --optimize-autoloader
          ./vendor/bin/phpunit
          EOF
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          VPS_IP: ${{ secrets.VPS_IP }}
