name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '7.4'
      #     extensions: mbstring, intl, bcmath
      #     coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-scripts --optimize-autoloader

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_USER: ${{ secrets.SSH_USER }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy
          chmod 600 ~/.ssh/deploy
          echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/deploy
          ssh-keyscan -H "$VPS_IP" >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no $SSH_USER@$VPS_IP <<EOF
          cd /var/www/adminci.infranetmp.com
          sudo git pull origin main
          composer install --no-interaction --prefer-dist --optimize-autoloader
          ./vendor/bin/phpunit
          EOF
