name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-scripts --optimize-autoloader

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_USER: ${{ secrets.SSH_USER }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          # Create the .ssh directory
          mkdir -p ~/.ssh

          # Add the private key to a file
          # echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa_new
          # chmod 600 /home/runner/.ssh/id_rsa_new

          # Start the ssh-agent
          eval $(ssh-agent -s)

          # Add the SSH key to the ssh-agent
          echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_rsa_new

          # Add the server to known hosts
          ssh-keyscan -H "$VPS_IP" >> ~/.ssh/known_hosts

          # Execute deployment commands using the specific key
          ssh -i /home/runner/.ssh/id_rsa_new -o StrictHostKeyChecking=no $SSH_USER@$VPS_IP <<EOF
          cd /var/www/adminci.infranetmp.com
          sudo git pull origin main
          composer install --no-interaction --prefer-dist --optimize-autoloader
          ./vendor/bin/phpunit
          EOF
